spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://mysql-db:3306/dangyo?serverTimezone=UTC&characterEncoding=utf8mb4&useUnicode=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      initialization-fail-timeout: -1

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000

dexcom:
  client-id: VdJNsY9IJPm8EFhIRAIQpxH923zeQkAY
  client-secret: 7Gc2AKoFnPigK0ca
  redirect-uri: http://localhost:8080/glucose/code
